### ISSUE TITLE
many bad links

### ISSUE THREAD

**Issue by leadingcode** [kopischke/alfred-workflows#5]
Many bad links in atticle :(

**Comment by kopischke** [comment]
Could you specify, please? I am not sure what you mean by this…

**Comment by leadingcode** [comment]
Ok,
In this page https://github.com/kopischke/alfred-workflows

**First link in articles** - link _Refresh Finder_ = 404 err.

[Disk space](https://github.com/kopischke/alfred-workflows#disk-space)
specified link to **Florian Pellet’s disk space workflow** but on the next page first link to dropbox is false = 404 err:  http://dl.dropbox.com/u/14050630/Disk%20space.alfredworkflow 

**Installing and updating**
[instaling and updating](https://github.com/kopischke/alfred-workflows#installing-and-updating)
Alleyoop: install Alleyoop - all links is bad

Thanks a lot!

**Comment by kopischke** [comment]
Thanks a lot for reporting, and apologies for not reacting, but all these are deprecated software. So are the workflows published here, as far as I am concerned: I haven’t been using Alfred since macOS revamped Spotlight, which is good enough for me, especially as my main work machine is an iPad by now. I will archive the repo, no fixes planned.
